version: '3.7'

services:
  db:
    image: postgres
    container_name: database-chapter-2
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=db_chapter_2
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: api-chapter-2
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - db
    depends_on:
      - db

volumes:
  pgdata:
    driver: local